### ISSUE TITLE
Include fields in search request

### ISSUE THREAD

**Issue by Thomas-Kuipers** [dutchcoders/marija#63]
When you make a search query, the socket message should also contain the selected fields. This is because the backend will only send the data for the selected fields to save on bandwidth.

@nl5887 What should the new structure for the message look like?

**Comment by nl5887** [comment]
Something like:

```
{
fields: ['a', 'b', 'c'],
query: 'query',
from: 0,
size: 100,
}
```

**Comment by Thomas-Kuipers** [comment]
Done, change is in branch thomas
