### ISSUE TITLE
Timed Indexes

### ISSUE THREAD

**Issue by danielguerra69** [dutchcoders/marija#85]
Is there a wildcard way for timed indices like myindex-2018-01-01 ?
Can I use myindex-* ?

**Comment by nl5887** [comment]
It looks like the fields for wildcard indices could not be retrieved. Something we need to work on.

**Comment by nl5887** [comment]
@danielguerra69 we've fixed the issue, you should be able to use wildcard indexes now.

**Comment by danielguerra69** [comment]
Thanx I will check it out !

**Comment by danielguerra69** [comment]
Works like a charm, now i can make schema's from my ip-lab. Like this research for "unknown" tls user-agents. Great !
<img width="1438" alt="screen shot 2018-07-07 at 15 57 58" src="https://user-images.githubusercontent.com/12379698/42411593-e4315840-81fe-11e8-8d3a-a02d27f7765c.png">
